src/main/java/com/javateknolojileri/model/Entry.java
package com.javateknolojileri.model;

import java.io.Serializable;
import java.util.Date;

public class Entry implements Serializable {

	private int id;
	private String title;
	private String body;
	private User author;
	private Date createDate;
	private Date publishDate;
	private User publishedBy;
	private EntryStatus status;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getBody() {
		return body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public User getAuthor() {
		return author;
	}

	public void setAuthor(User author) {
		this.author = author;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getPublishDate() {
		return publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public User getPublishedBy() {
		return publishedBy;
	}

	public void setPublishedBy(User publishedBy) {
		this.publishedBy = publishedBy;
	}

	public EntryStatus getStatus() {
		return status;
	}

	public void setStatus(EntryStatus status) {
		this.status = status;
	}

	public boolean isDraft() {
		return this.status == EntryStatus.DRAFT;
	}

	public boolean isDeleted() {
		return this.status == EntryStatus.DELETED;
	}

	public boolean isPublised() {
		return this.status == EntryStatus.PUBLISHED;
	}

	public boolean isWaitingForApprove() {
		return this.status == EntryStatus.WAITINGFORAPPROVE;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Entry other = (Entry) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Entry [id=" + id + ", title=" + title + ", body=" + body
				+ ", author=" + author + ", createDate=" + createDate
				+ ", publishDate=" + publishDate + ", publishedBy="
				+ publishedBy + ", status=" + status + "]";
	}

}

src/main/webapp/writer/entry/create.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="/template.xhtml">
	<ui:define name="content">
		<h:form>
			<h:panelGrid styleClass="width-max">
				<h:outputText value="Başlık" />
				<h:inputText value="#{writerEntryCreate.entry.title}"
					styleClass="width-max" />
				<h:outputText value="Yazı" />
				<h:inputTextarea value="#{writerEntryCreate.entry.body}"
					styleClass="width-max" style="height:400px;padding:5px;" />
				<h:commandButton action="#{writerEntryCreate.save()}" value="Kaydet"  styleClass="large"/>
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/writer/entry/edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="/template.xhtml">
	<ui:define name="content">
		<h:form>
			<h:panelGrid styleClass="width-max">
				<h:outputText value="Başlık" />
				<h:inputText value="#{writerEntryEdit.entry.title}"
					styleClass="width-max" />
				<h:outputText value="Yazı" />
				<h:inputTextarea value="#{writerEntryEdit.entry.body}"
					styleClass="width-max" style="height:400px;padding:5px;" />
				<h:commandButton action="#{writerEntryEdit.save()}" value="Kaydet" styleClass="large" />
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/writer/entry/list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="/template.xhtml">
	<ui:define name="content">
		<p>
			<h:button value="Yeni Yazı" outcome="/writer/entry/create" styleClass="large" />
		</p>
		<h:dataTable value="#{writerEntryList.entryList}" var="entry"
			styleClass="datatable">
			<h:column>
				<f:facet name="header">İşlem</f:facet>
				<h:link outcome="/writer/entry/edit" value="Düzenle">
					<f:param name="id" value="#{entry.id}" />
				</h:link>
				#{' '}
				<h:link outcome="/writer/entry/publish" value="Yayımla"
					rendered="#{entry.draft}">
					<f:param name="id" value="#{entry.id}" />
				</h:link>
			</h:column>

			<h:column>
				<f:facet name="header">Konu Başlığı</f:facet>
				<h:outputText value="#{entry.title}" />
			</h:column>
			<h:column>
				<f:facet name="header">Yazar</f:facet>
				<h:outputText value="#{entry.author.fullname}" />
			</h:column>
			<h:column>
				<f:facet name="header">Durum</f:facet>
				<h:outputText value="#{entry.status}" />
			</h:column>
		</h:dataTable>
	</ui:define>
</ui:composition>

src/main/webapp/writer/entry/publish.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="/template.xhtml">
	<ui:define name="content">
		<h:form>
			<p>
				<h:commandButton action="#{writerEntryPublish.save()}"
					value="Yayımla" styleClass="large" />
			</p>
			<div class="entry">
				<div class="entry-title">
					<h:outputText value="#{writerEntryPublish.entry.title}" />
				</div>

				<div class="entry-body">
					<h:outputText value="#{writerEntryPublish.entry.body}" escape="false" />
				</div>
				<div class="entry-footer">
					<h:outputText value="Yazar : #{writerEntryPublish.entry.author.fullname}" />
				</div>
			</div>
		</h:form>
	</ui:define>
</ui:composition>